// Generated by delombok at Sun Jan 19 19:44:26 CET 2025
package com.engine;

import javax.imageio.ImageIO;

import com.engine.Debug;
import com.engine.Vector2;

import java.awt.*;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.awt.image.ColorModel;
import java.awt.image.IndexColorModel;
import java.awt.image.RasterFormatException;
import java.awt.image.WritableRaster;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.LinkedList;

public class Sprite {
    private String src = "";
    private BufferedImage image = null;

    public Sprite(String src) {
        super();
        this.src = src;
        loadSprite(src);
    }

    public Sprite(String src, Rectangle region) {
        super();
        this.src = src;
        loadSprite(src,region);
    }


    public Sprite() {
    }

    public Sprite(BufferedImage image) {
        this.image = image;
    }

    public static LinkedList<Sprite> getSprites(String src) {
        LinkedList<Sprite> sprites = new LinkedList<>();
        File folder = new File(src);
        // Verify that the folder exists and is a directory
        if (folder.exists() && folder.isDirectory()) {
            // Get a list of all files in the folder
            File[] files = folder.listFiles();
            // Iterate through the files and print their names
            for (File file : files) {
                if (file.isFile()) {
                    sprites.add(new Sprite("/tiles/" + file.getName()));
                }
            }
        } else {
            System.out.println("Invalid folder path");
        }
        return sprites;
    }

    public static LinkedList<Sprite> getSprites(String src, LinkedList<Rectangle> boxes) {

        LinkedList<Sprite> animation = new LinkedList<>();
        for (Rectangle r : boxes) {
            Sprite sprite = new Sprite();
            sprite.loadSprite(src);

            BufferedImage animationSprite = (sprite.getImage().getSubimage((int) (r.getX()), (int) (r.getY()), (int) r.getWidth(), (int) r.getHeight()));
            sprite.setImage(animationSprite);
            animation.add(sprite);
        }
        return animation;
    }

    public void loadSprite(String filePath) {
        Debug.startCount();
        BufferedImage sprite = null;
        try {
            File file = new File(filePath); // Absolute or relative path
            sprite = ImageIO.read(file);
        } catch (IOException e) {
            e.printStackTrace();
        }
        this.image = sprite;
    }

    public void loadSprite(String filePath, Rectangle region) {
        Debug.startCount();
        BufferedImage sprite = null;
        try {
            File file = new File(filePath); // Absolute or relative path
            BufferedImage fullImage = ImageIO.read(file);
            sprite = fullImage.getSubimage(region.x, region.y, region.width, region.height);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (RasterFormatException e) {
            System.err.println("Region is outside the bounds of the image: " + e.getMessage());
        }
        this.image = sprite;
    }


    public void setSrc(final String src) {
        this.src = src;
    }



    public String getSrc() {
        return this.src;
    }



    public BufferedImage getImage() {
        return this.image;
    }



    public void setImage(final BufferedImage image) {
        this.image = image;
    }

    public static ArrayList<Sprite> getSprites(String src, Vector2 imageSize, Vector2 spriteAmount, Vector2 startStop){
        ArrayList<Sprite> annimation = new ArrayList<>();
        int w = (int)(imageSize.x/spriteAmount.x);
        int h = (int)(imageSize.y/spriteAmount.y);

        for(int x = 0; x < spriteAmount.x; x ++){
            Sprite sprite = new Sprite();
            sprite.loadSprite(src, new Rectangle(x*w,(int)(startStop.y*h),w,h));
            annimation.add(sprite);
        }

        return annimation;

    }
}
